name: ML CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training script
        run: |
          python scripts/train.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-files
          path: |
            trained_model.pkl
            metrics.json

  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-files

      - name: Read metrics
        run: |
          python <<EOF
          import json
          metrics = json.load(open("metrics.json"))

          r2 = metrics["R2"]
          best = float("${{ vars.BEST_F1_SCORE }}")

          print("Current R2:", r2)
          print("Best R2:", best)

          if r2 <= best:
              print("${{ github.actor }} ---- Metric did not improve")
              exit(0)
          EOF


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ridhima2022bcs0047:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ridhima2022bcs0047:latest
